[package]
name = "sdf_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpui = { version = "0.3.6" }
wgpui-kit = "0.6.1"
wgpu = { version = "30.0", default-features = false, features = ["vulkan", "wgsl"] }
cubecl = { version = "0.11.0-pre.2", features = ["wgpu"] }
cubecl-wgpu = "0.11.0-pre.2"
cubecl-runtime = "0.11.0-pre.2"
cubecl-zspace = "0.11.0-pre.2"
bytemuck = { version = "1.16", features = ["derive"] }
winit = { version = "0.30" }
tokio = { version = "1.38", features = ["full"] }
pollster = "0.3"
#...mouse system input
evdev = "0.12"
crossbeam-channel = "0.5"